In [119]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [143]:
dataset = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/laptop_price - dataset.csv", encoding="ISO-8859-1")
#X = dataset.iloc[:, :-1].values
#y = dataset.iloc[:, -1].values
selected_data = dataset[['CPU_Frequency (GHz)', 'RAM (GB)','OpSys','Weight (kg)', 'Price (Euro)']]

In [144]:
print(dataset.columns)

Index(['Company', 'Product', 'TypeName', 'Inches', 'ScreenResolution',
       'CPU_Company', 'CPU_Type', 'CPU_Frequency (GHz)', 'RAM (GB)', 'Memory',
       'GPU_Company', 'GPU_Type', 'OpSys', 'Weight (kg)', 'Price (Euro)'],
      dtype='object')


In [145]:
X = selected_data.iloc[:, :-1].values
y = selected_data.iloc[:, -1].values

"""selected_data = dataset[['Memory']].copy()
selected_data['Memory'] = selected_data['Memory'].astype(str)

selected_data = dataset[['GPU_Type']].copy()
selected_data['GPU_Type'] = selected_data['GPU_Type'].astype(str)

selected_data = dataset[['OpSys']].copy()  # Alt kümeyi kopyala
selected_data['OpSys'] = selected_data['OpSys'].astype(str)  # Dönüşüm işlemi"""


"selected_data = dataset[['Memory']].copy()\nselected_data['Memory'] = selected_data['Memory'].astype(str)\n\nselected_data = dataset[['GPU_Type']].copy()\nselected_data['GPU_Type'] = selected_data['GPU_Type'].astype(str) \n\nselected_data = dataset[['OpSys']].copy()  # Alt kümeyi kopyala\nselected_data['OpSys'] = selected_data['OpSys'].astype(str)  # Dönüşüm işlemi"

In [146]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[2] )], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [134]:
print(X)

[[2.3 8 'macOS' 1.37]
 [1.8 8 'macOS' 1.34]
 [2.5 8 'No OS' 1.86]
 ...
 [1.6 2 'Windows 10' 1.5]
 [2.5 6 'Windows 10' 2.19]
 [1.6 4 'Windows 10' 2.2]]


In [147]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [148]:
print(X_train)

[[0.0 0.0 0.0 ... 1.6 8 2.5]
 [0.0 0.0 0.0 ... 2.6 8 2.3]
 [0.0 0.0 0.0 ... 2.0 4 2.4]
 ...
 [0.0 0.0 0.0 ... 2.0 4 3.3]
 [0.0 0.0 0.0 ... 2.0 4 2.18]
 [0.0 0.0 0.0 ... 1.8 8 1.19]]


In [149]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [129]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 813.77  689.  ]
 [1299.57 1584.  ]
 [1279.94  999.  ]
 [1990.44 2397.  ]
 [ 905.25 1199.  ]
 [ 936.23  767.8 ]
 [ 601.88  479.  ]
 [1011.15  665.  ]
 [ 982.8   499.  ]
 [1221.41 1427.  ]
 [ 728.93  585.  ]
 [1282.57 2089.  ]
 [ 904.53 1129.  ]
 [1180.41  869.  ]
 [1175.05 1296.99]
 [ 898.5   400.  ]
 [ 912.76 1559.  ]
 [ 791.3   398.49]
 [1306.66 1599.  ]
 [ 672.44  649.  ]
 [ 757.48 1096.  ]
 [ 589.64  615.  ]
 [ 777.12  499.  ]
 [1137.88 1260.  ]
 [1100.44 1419.  ]
 [ 348.15  199.  ]
 [ 947.57  880.  ]
 [ 726.09  825.  ]
 [ 604.71  614.  ]
 [1214.94 1690.  ]
 [ 609.38  355.  ]
 [ 489.42  340.  ]
 [2828.92 2382.  ]
 [ 672.54  447.  ]
 [3339.66 5499.  ]
 [1194.68  745.  ]
 [1282.57 1292.  ]
 [1095.78  499.  ]
 [1655.93 2456.34]
 [1251.59  999.9 ]
 [1159.46 1390.  ]
 [1112.89 1579.  ]
 [1208.86 2249.  ]
 [1152.37  945.  ]
 [ 651.18  579.  ]
 [2069.92 2049.  ]
 [ 602.29  435.  ]
 [1208.55  520.9 ]
 [1871.37 1407.  ]
 [1899.72 1598.  ]
 [1107.01  589.52]
 [3536.48 4899.  ]
 [ 775.5   8

In [150]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.6585412563194836